fullnameOverride: radarr
image:
  repository: linuxserver/radarr
  tag: 5.26.2
port: 7878

volumes:
  - name: db
    claimName: db
  - name: data
    claimName: data
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/radarr
  - name: data
    mountPath: /downloads
    subPath: downloads
  - name: data
    mountPath: /movies
    subPath: library/movies