fullnameOverride: bazarr
image:
  repository: hotio/bazarr
  tag: release-1.4.3
port: 6767

nodePort:
  enabled: true
  port: 30676

ingress:
  enabled: false

volumes:
  - name: db
    claimName: db
  - name: data
    claimName: data
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/bazarr
  - name: data
    mountPath: /movies
    subPath: library/movies
  - name: data
    mountPath: /tv
    subPath: library/tv