fullnameOverride: sonarr
image:
  repository: linuxserver/sonarr
port: 8989

volumes:
  - name: media
    claimName: media
volumeMounts:
  - name: media
    mountPath: /config
    subPath: configs/sonarr
  - name: media
    mountPath: /downloads
    subPath: downloads
  - name: media
    mountPath: /tv
    subPath: library/tv