fullnameOverride: ghost
image:
  repository: ghost
  tag: 5.80.3
port: 2368

ingress:
  className: cloudflare
  host: ghost.dreamhomelab.online

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /var/lib/ghost/content
    subPath: configs/ghost

customEnv: true
env:
  - name: database__client
    value: mysql
  - name: database__connection__host
    value: mariadb
  - name: database__connection__port
    value: "3306"
  - name: database__connection__user
    value: root
  - name: database__connection__database
    value: ghost
  - name: url
    value: ghost.dreamhomelab.online
envSecret:
  - name: database__connection__password
    secretName: mariadb-secret
    secretKey: password