fullnameOverride: prowlarr
image:
  repository: lscr.io/linuxserver/prowlarr
  tag: develop
port: 9696
nodePort: 30696

services:
  clusterIP: false
  nodePort: true

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/prowlarr