fullnameOverride: prowlarr
image:
  repository: linuxserver/prowlarr
  tag: 2.0.5
port: 9696

nodePort:
  enabled: true
  port: 30696

ingress:
  enabled: false

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/prowlarr