fullnameOverride: prowlarr
image:
  repository: lscr.io/linuxserver/prowlarr
  tag: develop
port: 9696

nodePort:
  enabled: true
  port: 30696

ingress:
  enabled: false

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/prowlarr