fullnameOverride: jellyfin
image:
  repository: linuxserver/jellyfin
port: 8096
nodePort: 30096

gpuEnabled: true
resources:
  limits:
    nvidia.com/gpu: "1"

volumes:
  - name: db
    claimName: db
  - name: data
    claimName: data
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/jellyfin
  - name: data
    mountPath: /tv
    subPath: library/tv
  - name: data
    mountPath: /movies
    subPath: library/movies

customEnv: true
env:
  - name: NVIDIA_VISIBLE_DEVICES
    value: all
  - name: NVIDIA_DRIVER_CAPABILITIES
    value: all
  - name: JELLYFIN_FFmpeg__probesize
    value: "50000000"
  - name: JELLYFIN_FFmpeg__analyzeduration
    value: "50000000"