fullnameOverride: jellyfin
image:
  repository: linuxserver/jellyfin
port: 8096
nodePort: 30096

gpuEnabled: true

volumes:
  - name: db
    claimName: db
  - name: data
    claimName: data
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/jellyfin
  - name: data
    mountPath: /tv
    subPath: library/tv
  - name: data
    mountPath: /movies
    subPath: library/movies