fullnameOverride: jellyfin
image:
  repository: linuxserver/jellyfin
  tag: 10.10.7
port: 8096

volumes:
  - name: db
    claimName: db
  - name: data
    claimName: data
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/jellyfin
  - name: data
    mountPath: /tv
    subPath: library/tv
  - name: data
    mountPath: /tv-anime
    subPath: library/tv-anime
  - name: data
    mountPath: /movies
    subPath: library/movies
  - name: data
    mountPath: /movies-anime
    subPath: library/movies-anime

customEnv: true
env:
  - name: JELLYFIN_FFmpeg__probesize
    value: "50000000"
  - name: JELLYFIN_FFmpeg__analyzeduration
    value: "50000000"