fullnameOverride: transmission
image:
  repository: lscr.io/linuxserver/transmission
port: 9091
nodePort: 30091

services:
  clusterIP: false
  nodePort: true

additionalPorts:
  - enabled: true
    name: peer-tcp
    protocol: TCP
    type: ClusterIP
    port: 51413
  - enabled: true
    name: peer-udp
    protocol: UDP
    type: ClusterIP
    port: 51413

volumes:
  - name: db
    claimName: db
  - name: data
    claimName: data
volumeMounts:
  - name: data
    mountPath: /downloads
    subPath: downloads
  - name: db
    mountPath: /config
    subPath: configs/transmission

vpnEnabled: true