fullnameOverride: paperless
image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
port: 8000

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /usr/src/paperless/data
    subPath: configs/paperless/data
  - name: db
    mountPath: /usr/src/paperless/media
    subPath: configs/paperless/media
  - name: db
    mountPath: /usr/src/paperless/export
    subPath: configs/paperless/export
  - name: db
    mountPath: /usr/src/paperless/consume
    subPath: configs/paperless/consume

customEnv: true
env:
  - name: PAPERLESS_REDIS
    value: redis://redis:6379
  - name: PAPERLESS_DBHOST
    value: postgres
  - name: PAPERLESS_DBNAME
    value: paperless
  - name: PAPERLESS_PORT
    value: 8000
envSecret:
  - name: PAPERLESS_DBUSER
    secretName: postgres-secret
    secretKey: user
  - name: PAPERLESS_DBPASS
    secretName: postgres-secret
    secretKey: password