fullnameOverride: convertx
image:
  repository: c4illin/convertx
  tag: v0.9.0
port: 3000

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /app/data
    subPath: configs/convertx

customEnv: true
env:
  - name: ALLOW_UNAUTHENTICATED
    value: true