fullnameOverride: stirling
image:
  repository: frooodle/s-pdf
  tag: 0.35.0-fat
port: 8080

nodePort:
  enabled: true
  port: 30180

ingress:
  enabled: false

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /configs
    subPath: configs/stirling

customEnv: true
env:
  - name: DOCKER_ENABLE_SECURITY
    value: false