fullnameOverride: stirling
image:
  repository: frooodle/s-pdf
  tag: 0.35.0-fat
port: 8080

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /configs
    subPath: configs/stirling

customEnv: true
env:
  - name: DOCKER_ENABLE_SECURITY
    value: false
  - name: SYSTEM_ROOTURIPATH
    value: ""