apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbeaver
  namespace: {{ .Values.metadata.namespace }}
  finalizers: {{ .Values.metadata.finalizers }}
  labels:
    name: cloudbeaver
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    chart: {{ .Values.spec.source.chart }}
    path: lab/cloudbeaver
    helm:
      valueFiles: {{ .Values.spec.source.helm.valueFiles }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
