apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: {{ .Values.metadata.namespace }}
  finalizers: {{ .Values.metadata.finalizers }}
  labels:
    name: ghost
spec:
  project: {{ .Values.spec.project }}
  sources:
    - repoURL: https://maxenceng.github.io/easy-cloudflare-chart/
      targetRevision: 1.0.0
      chart: easy-cloudflare
      helm:
        valueFiles:
        - $values/lab/ghost/values.yaml
    - repoURL: {{ .Values.spec.values.repoURL }}
      targetRevision: {{ .Values.spec.values.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
