apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: {{ .Values.metadata.namespace }}
  finalizers: {{ .Values.metadata.finalizers }}
  labels:
    name: monitoring
spec:
  project: {{ .Values.spec.project }}
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 56.14.0
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/lab/monitoring/values.yaml
    - repoURL: https://github.com/maxenceng/home-lab
      targetRevision: HEAD
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true