apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: {{ .Values.metadata.namespace }}
  finalizers: {{ .Values.metadata.finalizers }}
  labels:
    name: postgres
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: https://github.com/maxenceng/home-lab.git
    targetRevision: HEAD
    path: lab/postgres
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true