{{- range .Values.pvc }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}-pv
spec:
  capacity:
    storage: {{ .storage }}
  accessModes:
    - {{ .accessMode }}
  hostPath:
    path: {{ .path }}
---
{{- end }}
{{- end }}

{{- range .Values.pvc }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
spec:
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .storage }}
---
{{- end }}
{{- end }}