fullnameOverride: vaultwarden
image:
  repository: vaultwarden/server
  tag: 1.34.3
port: 80

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /data
    subPath: configs/vaultwarden