fullnameOverride: flaresolverr
image:
  repository: alexfozor/flaresolverr
  tag: pr-1300-experimental
port: 8191

nodePort:
  enabled: true
  port: 30080

ingress:
  enabled: false

customEnv: true
env:
  - name: TZ
    value: Europe/London
  - name: CAPTCHA_SOLVER
    value: none
