---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-secret
  namespace: dev
spec:
  encryptedData:
    url: AgBCv8DUy3B6BBpZYuyTo8FqL9+eQ1Er4Q4bjE4xDyLfk1iSQKUTlK58Sss2hnFP6rlFB4aSnf+YoafSH0P8yMXP6r+NSHceoFI2GyzM2xVq68Y2/obhb3Cr5mclSXsiREADkwjkDDzMIceXM+gU/heYdS76ymiyZCTDNgq4dXUr79k/jF6nqpnH8YAp3TVTxYq1g+qt4g0a+p50uTsU8CBrRRKMlqV82yF0FMg0VNFHArbKF3Q89pMMC/88q5cFZU1RxjIyJSo5rI7ZYTRTfAOyAWd9wiq+Iw1uuQcflGH24+d6qdIKxfoyXOKE0y+Di6JbBmfnFVer8ONTkr0hXLaD0rm9fLdPWs+qjPlmjKNpbKd7qqOoEEcedBol0pSPYLYYLOE5ByoP1I9zMHwjpeuh/hzljL7Y5lxkYYBmT2BqmQl9HDRFS2oywvZU7zqyA4ID6Hd05T6/KhcerEkVrfC8JLjTfY33kktqmXEYaEmkTkS0OzDSAhzAvXTKcEwIDxY3TKKwIZucMFq6UMO+drUJN19G8iX3/qEZO/ylNH9+p7TtucUEu8ydEnQB7k9dswPZgZNtWrsgNaMeXeK3/qxI1cCBH5zOhlA+50VbXFxACokPw+VDYNg0WE/fnlCDlJt1zV82P/E7XU+F1AQ7mB4jFqk/lVR3p3N4c4E1XOD67jsT9jXLq3aH1grcpdeQFFmeD5SQxleZkY1EYP4pHirkMGArACHXPOyHBolfvVAWuY5WWQfSQQ==
  template:
    metadata:
      creationTimestamp: null
      name: paperless-secret
      namespace: dev
    type: Opaque
