---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: dev
spec:
  encryptedData:
    password: AgAenOZ7qZVneA87G8E+YBSSZIcl4f/D9QWd1WeVW6vHoD2u2nTZXzN2c03AyUoU7L5jR4D2f64koK49Mj92Hz/5wowenNR5+tntTZJlbNTkpYmHkHnQ70TUHOvVKaWZBTLrNdVUhbg/h0Hv+Ln1Smuhm96eD+lOMjxCYLJeGKULY2A07OYl04GC/FRTcM+QXs6GexngDM99fKtVfnkonr5WNVNGiC6wPscLJnuKUvMD/fmy1be1jAnW7zOGh2uMzLyib6J5t6Jfs4o/GLob9M9xD7is/xoYxjqwQ6DQE8s7fyzmDEv1hDCDS6Kf0WoczXpkx9cN7bb9/3pNLNPQnUNgJm9j1mR24FJGHl5ErhBDn5H4m23L/1N1YV5asw9kfdVFwpKaNn9PSS2z/xadN5xgYuTSP/iXw0milYsQQDF8EqeOUUCxPoldZGtOrk2YZaPx7jA41Ci2vSPnd0akMvutlaRUBGXtvr5mJUyTx5zfYg00Z5GNQQglcDYiocgqFrcV8/DH/4QApFfZOKa+EZ6wCOm9TbjFEGyM+MSb0/NhD2B5C/5FOXo6ZMHhZJVt64tbEcLsDd6UhR6Jgy7kq7lYSpDPov5sXb3DiJqRTS5kCeCXQhpHZzE9WLLQirr0OSMoTT/1qRWkfi7AQWoMTw9uHxEQPBdHOeQnBRo/iBLRd/gh7eyYiUrmPfZ3pHDe1IwsLMxVfPinXvBfnd/Tpg==
    user: AgCojm27p3M8xbE8P6xwzrc2U94tvu+MCovjJYtAqbRWlSXVsSnkHKoKY1SRM3XSC3cVuoKZcCjlHxfx+XmjNbJ3ZwbEAqN2D02oGGtVWFZW4CbfhFjDQKVk5ooCE5R8ooSQtHdvkuymWIWeqC6XEvUYgaXfsGsMfFOOug2xnioyraJWP4PtRC9mgNhAIOQj7wQFg24XqK/4d3Lp7KkHrS91lARJ8dN9OX0f2CecV/yxUakx6YLnQhHeMRYzSjdAijls4kTuV/EMFsosTy6nD8JjbuS6k15RFvk16hLwFq4CHmv4fpauK6uVKeQ4aDMvF7CJGf4z5DfkAqNMPrMwEsXqsLD8DqfT7FoR0+JOlJD5+rwZvwtTAHvUbb4jhnPIDlrhLX3wRBdvuqEuTbhFBWqmqP/8/fMOITxXqyDpeE9J7r9919/7I4Rt2B0owTqQL7dzBcLfqPYmfvZU9O0S1hBN3JzPPAPfIYJp2pywkYBNSg0qfzcKEVGgUsnQQ3N0diVYvICQ1IwOigHvLw5HMQwOfpRq4dE9OOTydkyEQZLIXtkumRRYKQQxfB0YJZIvRsEC2ZwJeU0098ryZd6mitaiDmXtvg2aQd2oQio3SElUljbYaCzhGQ1OoPjv36YDuyH7vxkiADmJragg42pEH8wK9nDETmZouPiL/Sf+SeawLhCLl/DKfZo+KYtIL/mwbd8vl8Dk2Q==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: dev
    type: Opaque
