---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: dev
spec:
  encryptedData:
    password: AgBTEJxIyc57oPtvu2qj0+hJp1mgT356E0LkhVD52UvCNpU2PIH369ql/ja+z/EHmJnFYgeh0mSoFBywbwwf0j2KWIPzthE1IklvKrUBWmwUiRbrI9B4bP1WZfapqhddKPJ16fNT7qS0gpdbEkYsGYK8p8zHdIQ8UQ0Y3ohrLu9n8wRG4QiPRUqGNOyvIh6L7FUwTMqXYxuJp9nlmPNG6OcG79Q9ZMinCD5Snq4L3Cq79wI+u/bVhP9OY8IYPj6HFfBKnddwQSjPxdD1kfXiRdlT1e3H3wQiPotC0zGD4h2KRE/OPzow+7kYXCD6DHkqlgc5SAeq3EORAvdp6ME+/H7UNijvkcaN+wP1gHBcXeoGoqZenb/xL5/pLdiPXvf5wBZ+8M9L6ucstaCVDSfahfW0qxK6pJGQNoUIIMt1OY9gDbo8fgj5Ddt1pZSdppWVdMVNz/ABpwRNGq088IbtPQ0JzYujAhk80A+5Na0SAtnUStRgZ20T6ieI7iv1zF32RGIU2YcRe8aSdgRDZOhgmnfzHJPoARnbvZPZFxx4CT/eiCLH4n/Hjc9CVB2UsGQmsKe3dyEcpmrrSly6xsu9CB7KVTsQc7Y3S3+9hbDFNM53+y9QcGCrlrsCwFjWIRkkiCeQ2cQpgnrpBZiR2YvtqZiHZ9Ttc0zQVQowY5Np1QnAmTDbJs6MkVpfGi4tj+PBSmHTrXVmWzC+VG91G0vubQ==
    user: AgBfJpPbFtc6ZGGPMsEfPAB4DLloS3uQK56TzS5sQkIXfB2CJ3PC5sdVhA+S+g11FuRUQmtWysIy3F9DV/NR4e0p+YBVUxBiNQ8czRSD8bzaeFzjTabqau5MH14YtCMcK/R9osl/5TK/iw4s/nPKAICcMC2ev1JKBwQkJ4eayVXwXaFQOntD9FL0s/Qn4AfvwM1LEhwYSdhp2PGqmaZLBfONiUM1DJ4m4Tt9tJgGHNL6j8iSSttB+S3IkB0/gozpIBFt5WXz9QzBBWa8pWXnvAqK75aICo3guWdGm66ljpxMn3sA4acaQDRJz5bxSmc1OQHT9s59eNwtLLNYFSWyqbjH/PSM07in0938g7Iz7rZfMaStwr9hEYwuPyIEI1s/mcLLHm03tOLM9MZPnuEzNlXcpWQtg7wPNbgbSfdEYgURNxbo3Wr0J0Rta/UjqMe2QT4OD2Af+eGmXAau7iDHsr5fSg+BXrldegCx84wEykgAxFbKEwNlXVvlL9d2wgppxE/Me7odNO8xdk5UTfyq/iQnXwz1xND37aHlQGErMgjk7inwoOCZHeWsuzeOwEsNRzPcJU4K8Y9aEsZsOnRGqFTHKBfHDBK069mH3WK/AIUmQW+sw6KONfFutvbjO8DhTxTSu7/ki1OQTgmiJDglsdsFO8ueMEIRe35nnE2ejMzpD1z5qZProcZ2uzAcJmP/6V6pl4LhhA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: dev
    type: Opaque
