# Example before sealing secret
# command : kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -f config/postgres-secret.yaml -w config/postgres-sealed.yaml

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  user: POSTGRES_USER
  password: POSTGRES_PASSWORD