apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi