apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/maxenceng/home-lab.git
    targetRevision: HEAD
    path: config
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true