fullnameOverride: jellyseerr
image:
  repository: fallenbagel/jellyseerr
  tag: 2.1.0
port: 5055

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /app/config
    subPath: configs/jellyseerr

customEnv: true
env:
  - name: TZ
    value: Europe/Zurich
  - name: LOG_LEVEL
    value: debug