metadata:
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://maxenceng.github.io/easy-tailscale-chart/
    targetRevision: 2.0.2
    chart: easy-tailscale
    helm:
      valueFiles:
        - values.yaml
  values:
    repoURL: https://github.com/maxenceng/home-lab
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: dev