fullnameOverride: komga
image:
  repository: gotson/komga
  tag: 1.14.1
port: 25600

volumes:
  - name: db
    claimName: db
  - name: data
    claimName: data
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/komga
  - name: data
    mountPath: /data
    subPath: library/comics

customEnv: true
env:
  - name: TZ
    value: Europe/Pairs