fullnameOverride: sonarr
image:
  repository: linuxserver/sonarr
port: 8989

volumes:
  - name: db
    claimName: db
  - name: data
    claimName: data
volumeMounts:
  - name: db
    mountPath: /config
    subPath: configs/sonarr
  - name: data
    mountPath: /downloads
    subPath: downloads
  - name: data
    mountPath: /tv
    subPath: library/tv