fullnameOverride: cloudbeaver
image:
  repository: dbeaver/cloudbeaver
  tag: 25.1.5
port: 8978

nodePort:
  enabled: true
  port: 31978

ingress:
  enabled: false

volumes:
  - name: db
    claimName: db
volumeMounts:
  - name: db
    mountPath: /opt/cloudbeaver/workspace
    subPath: configs/cloudbeaver